services:
  app:
    restart: always
    container_name: app-api-heroes-3-HOTA
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
