services:
  app:
    image: deno
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
